### ISSUE TITLE
CoreService.dll là build từ project nào

### ISSUE THREAD

**Issue by sanghv1987** [duccom0123/jx1-vs2022#7]
Chào duccom0123 mong bạn hỗ trợ. Mình rất muốn tham gia project này mà không biết liên hệ bạn kiểu gì: hoangsang.bg@gmail.com

**Comment by duccom0123** [comment]
Chỉ có CoreClient.dll và CoreServer.dll thôi bạn nhé. Build từ project Core.
Bạn có thể tham khảo để đóng góp code ở đây: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project
